name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - run: ruff check src tests

      - name: Run tests with coverage
        run: pytest --cov=src/guardian --cov-report=html --cov-report=term-missing

      - run: |
          coverage report --fail-under=70
          echo "Coverage is above 70%!!"

      - run: behave

      - run: sudo apt install -y shellcheck

      - run: shellcheck scripts/scan-repo.sh