name: Release

on:
  push:
    tags:
      - 'v*'
env:
  PACKAGE_NAME: 'repo-guardian'
  OWNER: "axvg"

jobs:
  build_source_dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python -m pip install build
      - run: python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: source-dist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheels

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheels/*.whl

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build_source_dist
      - build_wheels
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: source-dist
          path: dist/

      - name: Download Wheels (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: wheels/ubuntu/

      - name: Download Wheels (Windows)
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-2019
          path: wheels/windows/

      - name: Create gh release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
            dist/*.tar.gz \
            wheels/ubuntu/*.whl \
            wheels/windows/*.whl \
            --title "${{ github.ref_name }}" \
            --notes "Release de tag ${{ github.ref_name }}" \
            --target ${{ github.sha }}